export const AUDIT_ACTIONS = [
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',
  'LOGOUT',
  'AIRCON_POWER',
  'AIRCON_SET',
  'LIST_CREATE',
  'LIST_RENAME',
  'LIST_DELETE',
  'LIST_ITEM_CREATE',
  'LIST_ITEM_UPDATE',
  'LIST_ITEM_TOGGLE',
  'LIST_ITEM_DELETE',
  'LIST_SHARE_ADD',
  'LIST_SHARE_UPDATE',
  'LIST_SHARE_REMOVE',
  'USER_CREATE',
  'USER_UPDATE',
  'USER_ROLE_CHANGE',
  'USER_DELETE',
  'WEBAUTHN_REGISTER',
  'WEBAUTHN_REMOVE',
] as const;

export const AUDIT_ACTION_LABEL: Record<(typeof AUDIT_ACTIONS)[number], string> = {
  LOGIN_SUCCESS: 'ログイン成功',
  LOGIN_FAILURE: 'ログイン失敗',
  LOGOUT: 'ログアウト',
  AIRCON_POWER: 'エアコン電源操作',
  AIRCON_SET: 'エアコン設定変更',
  LIST_CREATE: 'リスト作成',
  LIST_RENAME: 'リスト名称変更',
  LIST_DELETE: 'リスト削除',
  LIST_ITEM_CREATE: '項目追加',
  LIST_ITEM_UPDATE: '項目編集',
  LIST_ITEM_TOGGLE: '項目完了切替',
  LIST_ITEM_DELETE: '項目削除',
  LIST_SHARE_ADD: '共有追加',
  LIST_SHARE_UPDATE: '共有権限変更',
  LIST_SHARE_REMOVE: '共有解除',
  USER_CREATE: 'ユーザー作成',
  USER_UPDATE: 'ユーザー情報変更',
  USER_ROLE_CHANGE: 'ロール変更',
  USER_DELETE: 'ユーザー削除',
  WEBAUTHN_REGISTER: 'パスキー登録',
  WEBAUTHN_REMOVE: 'パスキー削除',
};
